blueprint:
  name: picture_frame
  description: Automation to controll pi3d picture_frame
  domain: automation
  input:
    picture_frame:
      name: picture frame
      description: picture frame to use
      selector:
        device:
          integration: MQTT
          manufacturer: pi3d picture frame project
          model: Picture Frame
    fade_time:
      name: fade time
      description: Input helper to control fading timer
      selector:
        target:
          entity:
            domain: input_number
  variables:
    fade_time_state: !input fade_time
    picture_frame_id: !input picture_frame
  trigger:
      platform: state
      entity_id: !input fade_time
  action:
    service: mqtt.publish
    data:
      topic: [picture_frame_id]/fade_time
      payload: '{{ states[fade_time_state] }}'
